services:
  - type: web
    name: chatbot-rag-api
    env: docker
    dockerfilePath: docker/Dockerfile.api
    dockerContext: .
    plan: free
    region: oregon
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: USE_EMBEDDED_CHROMA
        value: true
      - key: CHROMA_PERSIST_DIR
        value: /data/vector_store
      - key: MODE
        value: production
    disk:
      name: vector-store
      mountPath: /data/vector_store
      sizeGB: 1
